package com.example.moneysplitter.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme — financial teal palette
val PrimaryLight = Color(0xFF006B5E)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF7CF8E0)
val OnPrimaryContainerLight = Color(0xFF00201B)
val SecondaryLight = Color(0xFF4A635D)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCDE8E0)
val OnSecondaryContainerLight = Color(0xFF06201B)
val TertiaryLight = Color(0xFF426278)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFC7E7FF)
val OnTertiaryContainerLight = Color(0xFF001E30)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val BackgroundLight = Color(0xFFFAFDFA)
val OnBackgroundLight = Color(0xFF191C1B)
val SurfaceLight = Color(0xFFFAFDFA)
val OnSurfaceLight = Color(0xFF191C1B)
val SurfaceVariantLight = Color(0xFFDBE5E0)
val OnSurfaceVariantLight = Color(0xFF3F4945)

// Dark theme
val PrimaryDark = Color(0xFF5DDBC4)
val OnPrimaryDark = Color(0xFF003830)
val PrimaryContainerDark = Color(0xFF005046)
val OnPrimaryContainerDark = Color(0xFF7CF8E0)
val SecondaryDark = Color(0xFFB1CCC4)
val OnSecondaryDark = Color(0xFF1D352F)
val SecondaryContainerDark = Color(0xFF334B46)
val OnSecondaryContainerDark = Color(0xFFCDE8E0)
val TertiaryDark = Color(0xFFAACBE3)
val OnTertiaryDark = Color(0xFF113347)
val TertiaryContainerDark = Color(0xFF2A4A5F)
val OnTertiaryContainerDark = Color(0xFFC7E7FF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val BackgroundDark = Color(0xFF191C1B)
val OnBackgroundDark = Color(0xFFE1E3E0)
val SurfaceDark = Color(0xFF191C1B)
val OnSurfaceDark = Color(0xFFE1E3E0)
val SurfaceVariantDark = Color(0xFF3F4945)
val OnSurfaceVariantDark = Color(0xFFBFC9C4)

// Semantic colors for balances
val PositiveGreen = Color(0xFF2E7D32)
val NegativeRed = Color(0xFFC62828)
val PositiveGreenDark = Color(0xFF81C784)
val NegativeRedDark = Color(0xFFEF9A9A)
