package com.example.traveltool.data

import java.util.UUID

/**
 * How the user travels.
 */
enum class TravelMode { CAR, MICROBUS, PLANE }

/**
 * Vehicle emission / fuel type — used by the Routes API toll computation.
 */
enum class VehicleEmissionType {
    GASOLINE, DIESEL, ELECTRIC;

    val label: String get() = when (this) {
        GASOLINE -> "⛽ Gasoline"
        DIESEL   -> "⛽ Diesel"
        ELECTRIC -> "⚡ Electric"
    }
}

/**
 * A toll road / vignette entry.
 */
data class TollRoad(
    val id: String = UUID.randomUUID().toString(),
    val name: String = "",
    val price: Double = 0.0,
    val currency: String = "EUR",
    val isAutoGenerated: Boolean = false
)

/**
 * A plane ticket entry.
 */
data class PlaneTicket(
    val id: String = UUID.randomUUID().toString(),
    val name: String = "",          // kept for display / legacy
    val fromAirport: String = "",   // IATA code or full name
    val toAirport: String = "",     // IATA code or full name
    val price: Double = 0.0,
    val currency: String = "EUR",
    val quantity: Int = 1,
)

/**
 * A car rental entry (only relevant when travelling by plane).
 */
data class CarRental(
    val id: String = UUID.randomUUID().toString(),
    val name: String = "",
    val price: Double = 0.0,
    val currency: String = "EUR",
)

/**
 * A public-transport fee auto-calculated or manually kept.
 */
data class PublicTransportFee(
    val id: String = UUID.randomUUID().toString(),
    val description: String = "",
    val price: Double = 0.0,
    val currency: String = "EUR",
    val isAutoGenerated: Boolean = true,
)

/**
 * An additional fee (baggage, insurance, etc.).
 */
data class AdditionalFee(
    val id: String = UUID.randomUUID().toString(),
    val name: String = "",
    val price: Double = 0.0,
    val currency: String = "EUR"
)

/**
 * Represents an accommodation within a trip.
 */
data class Accommodation(
    val id: String = UUID.randomUUID().toString(),
    val name: String = "",
    val startMillis: Long = 0L,
    val endMillis: Long = 0L,
    val pricePerNight: Double? = null,
    val priceCurrency: String = "EUR",
    val location: String = "",
    val latitude: Double? = null,
    val longitude: Double? = null,
) {
    /** True when any required field is missing / blank. */
    val hasWarning: Boolean
        get() = name.isBlank() || startMillis == 0L || endMillis == 0L || pricePerNight == null || location.isBlank()
}

/**
 * A daily spending entry.
 */
data class DailySpending(
    val id: String = UUID.randomUUID().toString(),
    val name: String = "",
    val amountPerDay: Double = 0.0,
    val currency: String = "EUR"
)

/**
 * An additional spending entry (non-daily).
 */
data class OtherSpending(
    val id: String = UUID.randomUUID().toString(),
    val name: String = "",
    val amount: Double = 0.0,
    val currency: String = "EUR"
)

/**
 * Per-day plan: stores departure time for the day's activities.
 */
data class DayPlan(
    val dayMillis: Long = 0L,
    val departureHour: Int = 9,
    val departureMinute: Int = 0,
    val movingDayDrivingDistanceKm: Double? = null,
)

/**
 * Position of an activity on a travel (moving) day.
 * On non-travel days this is not used.
 */
enum class TravelDayPosition(val label: String) {
    BEFORE_ARRIVAL("Before arrival (on the way)"),
    AFTER_ARRIVAL("After arrival"),
}

/**
 * Activity category.
 */
enum class ActivityCategory(val label: String, val emoji: String) {
    HIKING("Hiking", "🥾"),
    MUSEUM("Museum", "🏛️"),
    NICE_SIGHT("Nice sight", "📸"),
    BEACH("Beach", "🏖️"),
    WELLNESS("Wellness", "🧖"),
    EATING("Eating", "🍽️"),
    OTHER("Other", "📌");
}

/**
 * Sub-category for eating activities.
 */
enum class EatingType(val label: String) {
    BREAKFAST("Breakfast"),
    BRUNCH("Brunch"),
    LUNCH("Lunch"),
    DINNER("Dinner");
}

/**
 * A planned activity within a single trip day.
 * Activities chain sequentially: driving time is from the previous activity
 * (or accommodation for the first activity).
 */
data class Activity(
    val id: String = UUID.randomUUID().toString(),
    val dayMillis: Long = 0L,
    val name: String = "",
    val location: String = "",
    val durationMinutes: Int = 60,
    val orderIndex: Int = 0,
    val drivingTimeToMinutes: Int? = null,
    val drivingDistanceToKm: Double? = null,
    val returnDrivingTimeMinutes: Int? = null,
    val returnDrivingDistanceKm: Double? = null,
    val description: String = "",
    val rating: Double? = null,
    val photoUrl: String? = null,
    val category: String = "",
    val eatingType: String = "",
    val travelDayPosition: String = "",
    val isDelay: Boolean = false,
    val cost: Double = 0.0,
    val costCurrency: String = "EUR",
    val costMultiplier: Int = 1,
)

/**
 * Represents a saved trip.
 */
data class Trip(
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val startMillis: Long,
    val endMillis: Long,
    val location: String = "",
    val accommodations: List<Accommodation> = emptyList(),
    val startingPoint: String = "",
    val endingPoint: String = "",
    val travelMode: TravelMode = TravelMode.CAR,
    val vehicleEmissionType: VehicleEmissionType = VehicleEmissionType.GASOLINE,
    val fuelConsumption: Double? = null,
    val fuelPricePerLiter: Double? = null,
    val fuelPriceCurrency: String = "EUR",
    val tollRoads: List<TollRoad> = emptyList(),
    val planeTickets: List<PlaneTicket> = emptyList(),
    val carRentals: List<CarRental> = emptyList(),
    val publicTransportFees: List<PublicTransportFee> = emptyList(),
    val additionalFees: List<AdditionalFee> = emptyList(),
    val dailySpendings: List<DailySpending> = emptyList(),
    val otherSpendings: List<OtherSpending> = emptyList(),
    val activities: List<Activity> = emptyList(),
    val dayPlans: List<DayPlan> = emptyList(),
    val displayCurrency: String = "EUR",
    val estimatedDrivingDistanceKm: Double? = null
) {
    /** True when accommodations list is empty or any accommodation has a warning. */
    val hasWarning: Boolean
        get() = accommodations.isEmpty() || accommodations.any { it.hasWarning }
}
