package com.example.traveltool.data

import java.util.UUID

/**
 * How the user travels.
 */
enum class TravelMode { CAR, MICROBUS, PLANE }

/**
 * A toll road / vignette entry.
 */
data class TollRoad(
    val id: String = UUID.randomUUID().toString(),
    val name: String = "",
    val price: Double = 0.0,
    val currency: String = "EUR",
    val isAutoGenerated: Boolean = false
)

/**
 * A plane ticket entry.
 */
data class PlaneTicket(
    val id: String = UUID.randomUUID().toString(),
    val name: String = "",
    val price: Double = 0.0,
    val currency: String = "EUR"
)

/**
 * An additional fee (baggage, insurance, etc.).
 */
data class AdditionalFee(
    val id: String = UUID.randomUUID().toString(),
    val name: String = "",
    val price: Double = 0.0,
    val currency: String = "EUR"
)

/**
 * Represents an accommodation within a trip.
 */
data class Accommodation(
    val id: String = UUID.randomUUID().toString(),
    val name: String = "",
    val startMillis: Long = 0L,
    val endMillis: Long = 0L,
    val pricePerNight: Double? = null,
    val priceCurrency: String = "EUR",
    val location: String = ""
) {
    /** True when any required field is missing / blank. */
    val hasWarning: Boolean
        get() = name.isBlank() || startMillis == 0L || endMillis == 0L || pricePerNight == null || location.isBlank()
}

/**
 * A daily spending entry.
 */
data class DailySpending(
    val id: String = UUID.randomUUID().toString(),
    val name: String = "",
    val amountPerDay: Double = 0.0,
    val currency: String = "EUR"
)

/**
 * An additional spending entry (non-daily).
 */
data class OtherSpending(
    val id: String = UUID.randomUUID().toString(),
    val name: String = "",
    val amount: Double = 0.0,
    val currency: String = "EUR"
)

/**
 * Represents a saved trip.
 */
data class Trip(
    val id: String = UUID.randomUUID().toString(),
    val name: String,
    val startMillis: Long,
    val endMillis: Long,
    val location: String,
    val accommodations: List<Accommodation> = emptyList(),
    val startingPoint: String = "",
    val travelMode: TravelMode = TravelMode.CAR,
    val fuelConsumption: Double? = null,
    val fuelPricePerLiter: Double? = null,
    val fuelPriceCurrency: String = "EUR",
    val tollRoads: List<TollRoad> = emptyList(),
    val planeTickets: List<PlaneTicket> = emptyList(),
    val additionalFees: List<AdditionalFee> = emptyList(),
    val dailySpendings: List<DailySpending> = emptyList(),
    val otherSpendings: List<OtherSpending> = emptyList(),
    val displayCurrency: String = "EUR"
) {
    /** True when accommodations list is empty or any accommodation has a warning. */
    val hasWarning: Boolean
        get() = accommodations.isEmpty() || accommodations.any { it.hasWarning }
}
