package com.example.traveltool.ui.screens

import android.location.Geocoder
import android.widget.Toast
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Search
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.focus.onFocusChanged
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.traveltool.data.*
import com.example.traveltool.ui.components.CurrencyPicker
import com.example.traveltool.ui.theme.*
import com.google.android.gms.maps.CameraUpdateFactory
import com.google.android.gms.maps.model.CameraPosition
import com.google.android.gms.maps.model.LatLng
import com.google.maps.android.compose.GoogleMap
import com.google.maps.android.compose.Marker
import com.google.maps.android.compose.MarkerState
import com.google.maps.android.compose.rememberCameraPositionState
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.util.*

/**
 * Screen to edit an existing activity.
 * Allows changing name, location, duration, category, and description.
 * Recalculates driving time when the location changes.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun EditActivityScreen(
    tripId: String,
    activityId: String,
    tripViewModel: TripViewModel,
    onBack: () -> Unit,
) {
    val colors = LocalAppColors.current
    val trip = tripViewModel.getTripById(tripId)
    val activity = trip?.activities?.find { it.id == activityId }
    if (trip == null || activity == null) { onBack(); return }

    val context = LocalContext.current
    val scope = rememberCoroutineScope()

    var name by remember { mutableStateOf(activity.name) }
    var location by remember { mutableStateOf(activity.location) }

    // Track whether the name was auto-generated or user-provided
    fun autoName(loc: String) = if (loc.isNotBlank()) "Activity at $loc" else ""
    var nameIsAutoGenerated by remember {
        mutableStateOf(activity.name.isBlank() || activity.name == autoName(activity.location))
    }

    // When location changes and name is still auto-generated, update name
    LaunchedEffect(location) {
        if (nameIsAutoGenerated) {
            name = autoName(location.trim())
        }
    }
    var durationText by remember { mutableStateOf(activity.durationMinutes.toString()) }
    var description by remember { mutableStateOf(activity.description) }
    var selectedCategory by remember { mutableStateOf(activity.category) }
    var selectedEatingType by remember { mutableStateOf(activity.eatingType) }
    var markerPosition by remember { mutableStateOf<LatLng?>(null) }
    var isSaving by remember { mutableStateOf(false) }
    var showDeleteDialog by remember { mutableStateOf(false) }
    val isDelay = activity.isDelay
    var costText by remember { mutableStateOf(if (activity.cost > 0) activity.cost.toString() else "0") }
    var costCurrency by remember { mutableStateOf(activity.costCurrency) }
    var costMultiplier by remember { mutableStateOf(activity.costMultiplier) }
    val currencies = remember { CurrencyManager.getCurrencyList(context) }

    // Track whether location changed (to recalculate driving time)
    val locationChanged = location.trim() != activity.location.trim()

    val cameraPositionState = rememberCameraPositionState {
        position = CameraPosition.fromLatLngZoom(LatLng(48.8566, 2.3522), 5f)
    }

    // Geocode original location on mount
    LaunchedEffect(activity.location) {
        if (activity.location.isNotBlank()) {
            val result = withContext(Dispatchers.IO) {
                try {
                    @Suppress("DEPRECATION")
                    val geocoder = Geocoder(context, Locale.getDefault())
                    val addresses = geocoder.getFromLocationName(activity.location.trim(), 1)
                    if (!addresses.isNullOrEmpty()) {
                        LatLng(addresses[0].latitude, addresses[0].longitude)
                    } else null
                } catch (_: Exception) { null }
            }
            if (result != null) {
                markerPosition = result
                cameraPositionState.animate(CameraUpdateFactory.newLatLngZoom(result, 12f))
            }
        }
    }

    // Determine "from" location (previous activity or accommodation)
    val existingActivities = tripViewModel.getActivitiesForDay(tripId, activity.dayMillis)
    val todayAccom = trip.accommodations.find {
        it.startMillis <= activity.dayMillis && activity.dayMillis < it.endMillis
    } ?: trip.accommodations.find {
        it.startMillis <= activity.dayMillis && activity.dayMillis <= it.endMillis
    }

    // Previous day accommodation (for moving day detection)
    val prevDayAccom = remember(trip.accommodations, activity.dayMillis) {
        if (activity.dayMillis > trip.startMillis) {
            val prevDay = activity.dayMillis - 24 * 60 * 60 * 1000L
            trip.accommodations.find { it.startMillis <= prevDay && prevDay < it.endMillis }
                ?: trip.accommodations.find { it.startMillis <= prevDay && prevDay <= it.endMillis }
        } else null
    }

    val isFinalDay = activity.dayMillis >= trip.endMillis
    val isMovingDay = remember(todayAccom, prevDayAccom, activity.dayMillis, trip.startMillis, trip.endMillis) {
        when {
            activity.dayMillis == trip.startMillis -> true
            isFinalDay -> true
            todayAccom == null -> false
            prevDayAccom == null -> true
            prevDayAccom.location != todayAccom.location -> true
            else -> false
        }
    }

    // Travel day position (preserve existing value)
    var selectedPosition by remember { mutableStateOf(activity.travelDayPosition.ifBlank { TravelDayPosition.AFTER_ARRIVAL.name }) }

    val originLocation = when {
        activity.dayMillis == trip.startMillis -> trip.startingPoint
        prevDayAccom != null -> prevDayAccom.location
        todayAccom != null -> todayAccom.location
        else -> trip.startingPoint
    }
    val destLocation = when {
        isFinalDay -> trip.endingPoint.ifBlank { trip.startingPoint }
        todayAccom != null -> todayAccom.location
        else -> trip.startingPoint
    }

    val prevActivity = if (isMovingDay) {
        val sameGroup = existingActivities.filter {
            if (selectedPosition == TravelDayPosition.BEFORE_ARRIVAL.name)
                it.travelDayPosition == TravelDayPosition.BEFORE_ARRIVAL.name
            else
                it.travelDayPosition != TravelDayPosition.BEFORE_ARRIVAL.name
        }.filter { it.orderIndex < activity.orderIndex }
        sameGroup.maxByOrNull { it.orderIndex }
    } else {
        existingActivities.filter { it.orderIndex < activity.orderIndex }.maxByOrNull { it.orderIndex }
    }

    val fromLocation = if (isMovingDay) {
        prevActivity?.location ?: if (selectedPosition == TravelDayPosition.BEFORE_ARRIVAL.name) originLocation else destLocation
    } else {
        prevActivity?.location
            ?: todayAccom?.location?.ifBlank { trip.startingPoint }
            ?: trip.startingPoint
    }

    fun searchLocation() {
        if (location.isBlank()) return
        scope.launch {
            val result = withContext(Dispatchers.IO) {
                try {
                    @Suppress("DEPRECATION")
                    val geocoder = Geocoder(context, Locale.getDefault())
                    val addresses = geocoder.getFromLocationName(location.trim(), 1)
                    if (!addresses.isNullOrEmpty()) {
                        LatLng(addresses[0].latitude, addresses[0].longitude)
                    } else null
                } catch (_: Exception) { null }
            }
            if (result != null) {
                markerPosition = result
                cameraPositionState.animate(CameraUpdateFactory.newLatLngZoom(result, 12f))
            } else {
                Toast.makeText(context, "Location not found", Toast.LENGTH_SHORT).show()
            }
        }
    }

    val canSave = (isDelay || location.isNotBlank()) && !isSaving
    val durationMinutes = durationText.toIntOrNull() ?: 60

    // Delete confirmation dialog
    if (showDeleteDialog) {
        AlertDialog(
            onDismissRequest = { showDeleteDialog = false },
            title = { Text("Delete Activity") },
            text = { Text("Are you sure you want to delete \"${activity.name}\"?") },
            confirmButton = {
                TextButton(
                    onClick = {
                        tripViewModel.deleteActivity(tripId, activityId)
                        showDeleteDialog = false
                        onBack()
                    },
                    colors = ButtonDefaults.textButtonColors(contentColor = colors.red),
                ) {
                    Text("Delete")
                }
            },
            dismissButton = {
                TextButton(onClick = { showDeleteDialog = false }) {
                    Text("Cancel")
                }
            }
        )
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Edit Activity") },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
                actions = {
                    IconButton(onClick = { showDeleteDialog = true }) {
                        Icon(
                            Icons.Default.Delete,
                            contentDescription = "Delete",
                            tint = colors.red,
                        )
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.surface,
                    titleContentColor = MaterialTheme.colorScheme.onSurface,
                )
            )
        },
        bottomBar = {
            Surface(
                tonalElevation = 4.dp,
                color = MaterialTheme.colorScheme.surface,
            ) {
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .navigationBarsPadding()
                        .padding(horizontal = 24.dp, vertical = 12.dp),
                ) {
                    Button(
                        onClick = {
                            isSaving = true
                            val apiKey = ApiKeyStore.getOpenAiKey(context)
                            val model = ApiKeyStore.getOpenAiModel(context)
                            val googleKey = try {
                                val appInfo = context.packageManager.getApplicationInfo(
                                    context.packageName,
                                    android.content.pm.PackageManager.GET_META_DATA
                                )
                                appInfo.metaData?.getString("com.google.android.geo.API_KEY") ?: ""
                            } catch (_: Exception) { "" }
                            scope.launch {
                                // Recalculate driving time if location changed
                                var drivingTo: Int? = activity.drivingTimeToMinutes
                                var drivingDistTo: Double? = activity.drivingDistanceToKm
                                var returnTime: Int? = activity.returnDrivingTimeMinutes
                                var returnDist: Double? = activity.returnDrivingDistanceKm

                                if (locationChanged && fromLocation.isNotBlank()) {
                                    val est = DirectionsApiHelper.estimateDrivingTime(
                                        from = fromLocation,
                                        to = location.trim(),
                                        googleApiKey = googleKey,
                                        openAiApiKey = apiKey,
                                        model = model,
                                    )
                                    drivingTo = est?.timeMinutes
                                    drivingDistTo = est?.distanceKm
                                }

                                // Recalculate return drive if this is the last activity in its group and location changed
                                val sameGroupActivities = if (isMovingDay) {
                                    existingActivities.filter {
                                        if (selectedPosition == TravelDayPosition.BEFORE_ARRIVAL.name)
                                            it.travelDayPosition == TravelDayPosition.BEFORE_ARRIVAL.name
                                        else
                                            it.travelDayPosition != TravelDayPosition.BEFORE_ARRIVAL.name
                                    }
                                } else existingActivities
                                val isLastInGroup = sameGroupActivities.none { it.orderIndex > activity.orderIndex }
                                if (isLastInGroup && locationChanged) {
                                    val returnTo = if (isFinalDay) {
                                        trip.endingPoint.ifBlank { trip.startingPoint.ifBlank { null } }
                                    } else {
                                        todayAccom?.location?.ifBlank { null }
                                            ?: trip.startingPoint.ifBlank { null }
                                    }
                                    if (apiKey.isNotBlank() && returnTo != null) {
                                        val retEst = DirectionsApiHelper.estimateDrivingTime(
                                            from = location.trim(),
                                            to = returnTo,
                                            googleApiKey = googleKey,
                                            openAiApiKey = apiKey,
                                            model = model,
                                        )
                                        returnTime = retEst?.timeMinutes
                                        returnDist = retEst?.distanceKm
                                    }
                                }

                                val updated = activity.copy(
                                    name = name.trim().ifBlank { autoName(location.trim()) },
                                    location = location.trim(),
                                    durationMinutes = durationMinutes,
                                    drivingTimeToMinutes = drivingTo,
                                    drivingDistanceToKm = drivingDistTo,
                                    returnDrivingTimeMinutes = returnTime,
                                    returnDrivingDistanceKm = returnDist,
                                    description = description.trim(),
                                    category = selectedCategory,
                                    eatingType = selectedEatingType,
                                    travelDayPosition = if (isMovingDay) selectedPosition else "",
                                    cost = costText.toDoubleOrNull() ?: 0.0,
                                    costCurrency = costCurrency,
                                    costMultiplier = costMultiplier,
                                )
                                tripViewModel.updateActivity(tripId, updated)
                                isSaving = false
                                onBack()
                            }
                        },
                        enabled = canSave,
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(52.dp),
                        colors = ButtonDefaults.buttonColors(
                            containerColor = colors.green,
                            contentColor = MaterialTheme.colorScheme.background,
                        )
                    ) {
                        if (isSaving) {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                CircularProgressIndicator(
                                    modifier = Modifier.size(20.dp),
                                    strokeWidth = 2.dp,
                                    color = MaterialTheme.colorScheme.background,
                                )
                                Spacer(Modifier.width(12.dp))
                                Text("Estimating travel time\u2026", fontWeight = FontWeight.Bold, fontSize = 16.sp)
                            }
                        } else {
                            Text("Save Changes", fontWeight = FontWeight.Bold, fontSize = 16.sp)
                        }
                    }
                }
            }
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .verticalScroll(rememberScrollState()),
        ) {
            Spacer(Modifier.height(12.dp))

            if (isDelay) {
                // --- Delay mode: show info card + name + duration ---
                Card(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 24.dp),
                    shape = RoundedCornerShape(12.dp),
                    colors = CardDefaults.cardColors(containerColor = colors.current),
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text("⏳ Delay activity", fontSize = 14.sp, fontWeight = FontWeight.Medium, color = colors.primary)
                        Spacer(Modifier.height(8.dp))
                        Text(
                            text = "📍 At: ${activity.location}",
                            fontSize = 13.sp,
                            color = colors.comment,
                        )
                        Text(
                            text = "No driving — waiting at the current location.",
                            fontSize = 11.sp,
                            color = colors.comment,
                        )
                    }
                }
                Spacer(Modifier.height(12.dp))

                // --- Name ---
                OutlinedTextField(
                    value = name,
                    onValueChange = { name = it },
                    label = { Text("Name") },
                    placeholder = { Text("Delay") },
                    singleLine = true,
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 24.dp),
                    colors = OutlinedTextFieldDefaults.colors(
                        focusedBorderColor = colors.primary,
                        focusedLabelColor = colors.primary,
                        cursorColor = colors.primary,
                    )
                )
                Spacer(Modifier.height(12.dp))

                // --- Duration ---
                OutlinedTextField(
                    value = durationText,
                    onValueChange = { durationText = it },
                    label = { Text("Duration (minutes)") },
                    singleLine = true,
                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 24.dp),
                    colors = OutlinedTextFieldDefaults.colors(
                        focusedBorderColor = colors.primary,
                        focusedLabelColor = colors.primary,
                        cursorColor = colors.primary,
                    )
                )

                Spacer(Modifier.height(12.dp))

                // --- Cost (delay mode) ---
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 24.dp),
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                    verticalAlignment = Alignment.CenterVertically,
                ) {
                    OutlinedTextField(
                        value = costText,
                        onValueChange = { costText = it },
                        label = { Text("Cost") },
                        singleLine = true,
                        keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal),
                        modifier = Modifier
                            .weight(1f)
                            .onFocusChanged { if (it.isFocused && costText == "0") costText = "" },
                        colors = OutlinedTextFieldDefaults.colors(
                            focusedBorderColor = colors.primary,
                            focusedLabelColor = colors.primary,
                            cursorColor = colors.primary,
                        )
                    )
                    Text("\u00d7", fontSize = 18.sp, color = colors.comment)
                    var mulExpanded by remember { mutableStateOf(false) }
                    ExposedDropdownMenuBox(
                        expanded = mulExpanded,
                        onExpandedChange = { mulExpanded = it },
                    ) {
                        OutlinedTextField(
                            value = costMultiplier.toString(),
                            onValueChange = {},
                            readOnly = true,
                            singleLine = true,
                            label = { Text("Mul.", fontSize = 11.sp) },
                            modifier = Modifier
                                .menuAnchor()
                                .width(80.dp),
                            trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(mulExpanded) },
                            colors = OutlinedTextFieldDefaults.colors(
                                focusedBorderColor = colors.primary,
                                focusedLabelColor = colors.primary,
                            ),
                            textStyle = LocalTextStyle.current.copy(fontSize = 14.sp),
                        )
                        ExposedDropdownMenu(
                            expanded = mulExpanded,
                            onDismissRequest = { mulExpanded = false },
                        ) {
                            (1..30).forEach { n ->
                                DropdownMenuItem(
                                    text = { Text("$n") },
                                    onClick = { costMultiplier = n; mulExpanded = false },
                                )
                            }
                        }
                    }
                    CurrencyPicker(
                        selected = costCurrency,
                        currencies = currencies,
                        onSelect = { costCurrency = it },
                    )
                }
            } else {

            // ── Travel day position picker (only on moving days) ──
            if (isMovingDay) {
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 24.dp, vertical = 4.dp),
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                ) {
                    FilterChip(
                        selected = selectedPosition == TravelDayPosition.BEFORE_ARRIVAL.name,
                        onClick = { selectedPosition = TravelDayPosition.BEFORE_ARRIVAL.name },
                        label = { Text("\uD83D\uDEE3\uFE0F On the way") },
                        modifier = Modifier.weight(1f),
                        colors = FilterChipDefaults.filterChipColors(
                            selectedContainerColor = colors.orange.copy(alpha = 0.2f),
                            selectedLabelColor = colors.orange,
                        ),
                    )
                    FilterChip(
                        selected = selectedPosition == TravelDayPosition.AFTER_ARRIVAL.name,
                        onClick = { selectedPosition = TravelDayPosition.AFTER_ARRIVAL.name },
                        label = { Text("\uD83C\uDFE8 After arrival") },
                        modifier = Modifier.weight(1f),
                        colors = FilterChipDefaults.filterChipColors(
                            selectedContainerColor = colors.green.copy(alpha = 0.2f),
                            selectedLabelColor = colors.green,
                        ),
                    )
                }
                Spacer(Modifier.height(8.dp))
            }

            // --- Location with search ---
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 24.dp),
                horizontalArrangement = Arrangement.spacedBy(8.dp),
            ) {
                OutlinedTextField(
                    value = location,
                    onValueChange = { location = it },
                    label = { Text("Location") },
                    placeholder = { Text("e.g. Eiffel Tower, Paris") },
                    leadingIcon = { Icon(Icons.Default.Search, contentDescription = null) },
                    singleLine = true,
                    modifier = Modifier.weight(1f),
                    colors = OutlinedTextFieldDefaults.colors(
                        focusedBorderColor = colors.primary,
                        focusedLabelColor = colors.primary,
                        cursorColor = colors.primary,
                    )
                )
                FilledIconButton(
                    onClick = { searchLocation() },
                    enabled = location.isNotBlank(),
                    modifier = Modifier.height(56.dp).width(56.dp),
                    colors = IconButtonDefaults.filledIconButtonColors(
                        containerColor = colors.primary,
                        contentColor = colors.foreground,
                    )
                ) {
                    Icon(Icons.Default.Search, contentDescription = "Search location")
                }
            }

            if (locationChanged) {
                Text(
                    text = "Location changed — driving time will be re-estimated on save.",
                    fontSize = 11.sp,
                    color = colors.orange,
                    modifier = Modifier.padding(horizontal = 24.dp, vertical = 4.dp),
                )
            }

            Spacer(Modifier.height(12.dp))

            // --- Mini map ---
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(160.dp)
                    .padding(horizontal = 24.dp)
                    .clip(RoundedCornerShape(12.dp)),
            ) {
                GoogleMap(
                    modifier = Modifier.fillMaxSize(),
                    cameraPositionState = cameraPositionState,
                ) {
                    markerPosition?.let { pos ->
                        Marker(
                            state = MarkerState(position = pos),
                            title = location.ifBlank { "Location" },
                        )
                    }
                }
            }

            Spacer(Modifier.height(12.dp))

            // --- Activity name (auto-filled from location) ---
            OutlinedTextField(
                value = name,
                onValueChange = {
                    name = it
                    nameIsAutoGenerated = false
                },
                label = { Text("Activity name") },
                singleLine = true,
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 24.dp)
                    .onFocusChanged { focusState ->
                        if (focusState.isFocused && nameIsAutoGenerated && name.isNotBlank()) {
                            name = ""
                            nameIsAutoGenerated = false
                        } else if (!focusState.isFocused && name.isBlank() && location.isNotBlank()) {
                            name = autoName(location.trim())
                            nameIsAutoGenerated = true
                        }
                    },
                colors = OutlinedTextFieldDefaults.colors(
                    focusedBorderColor = colors.primary,
                    focusedLabelColor = colors.primary,
                    cursorColor = colors.primary,
                )
            )

            Spacer(Modifier.height(16.dp))

            // --- Duration ---
            OutlinedTextField(
                value = durationText,
                onValueChange = { durationText = it },
                label = { Text("Time at activity (minutes)") },
                singleLine = true,
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 24.dp),
                colors = OutlinedTextFieldDefaults.colors(
                    focusedBorderColor = colors.primary,
                    focusedLabelColor = colors.primary,
                    cursorColor = colors.primary,
                )
            )

            Spacer(Modifier.height(16.dp))

            // --- Cost ---
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 24.dp),
                horizontalArrangement = Arrangement.spacedBy(8.dp),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                OutlinedTextField(
                    value = costText,
                    onValueChange = { costText = it },
                    label = { Text("Cost") },
                    singleLine = true,
                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal),
                    modifier = Modifier
                        .weight(1f)
                        .onFocusChanged { if (it.isFocused && costText == "0") costText = "" },
                    colors = OutlinedTextFieldDefaults.colors(
                        focusedBorderColor = colors.primary,
                        focusedLabelColor = colors.primary,
                        cursorColor = colors.primary,
                    )
                )
                Text("\u00d7", fontSize = 18.sp, color = colors.comment)
                var mulExpanded by remember { mutableStateOf(false) }
                ExposedDropdownMenuBox(
                    expanded = mulExpanded,
                    onExpandedChange = { mulExpanded = it },
                ) {
                    OutlinedTextField(
                        value = costMultiplier.toString(),
                        onValueChange = {},
                        readOnly = true,
                        singleLine = true,
                        label = { Text("Mul.", fontSize = 11.sp) },
                        modifier = Modifier
                            .menuAnchor()
                            .width(80.dp),
                        trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(mulExpanded) },
                        colors = OutlinedTextFieldDefaults.colors(
                            focusedBorderColor = colors.primary,
                            focusedLabelColor = colors.primary,
                        ),
                        textStyle = LocalTextStyle.current.copy(fontSize = 14.sp),
                    )
                    ExposedDropdownMenu(
                        expanded = mulExpanded,
                        onDismissRequest = { mulExpanded = false },
                    ) {
                        (1..30).forEach { n ->
                            DropdownMenuItem(
                                text = { Text("$n") },
                                onClick = { costMultiplier = n; mulExpanded = false },
                            )
                        }
                    }
                }
                CurrencyPicker(
                    selected = costCurrency,
                    currencies = currencies,
                    onSelect = { costCurrency = it },
                )
            }

            Spacer(Modifier.height(16.dp))

            // --- Description ---
            OutlinedTextField(
                value = description,
                onValueChange = { description = it },
                label = { Text("Description (optional)") },
                singleLine = false,
                maxLines = 3,
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 24.dp),
                colors = OutlinedTextFieldDefaults.colors(
                    focusedBorderColor = colors.primary,
                    focusedLabelColor = colors.primary,
                    cursorColor = colors.primary,
                )
            )

            Spacer(Modifier.height(16.dp))

            // --- Driving time info ---
            if (activity.drivingTimeToMinutes != null && !locationChanged) {
                Card(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 24.dp),
                    shape = RoundedCornerShape(12.dp),
                    colors = CardDefaults.cardColors(containerColor = colors.current),
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text("Current driving time", fontSize = 14.sp, fontWeight = FontWeight.Medium, color = colors.primary)
                        Spacer(Modifier.height(8.dp))
                        val h = activity.drivingTimeToMinutes / 60
                        val m = activity.drivingTimeToMinutes % 60
                        Text(
                            text = "\uD83D\uDE97 ${if (h > 0) "${h}h " else ""}${m}min from ${fromLocation.take(30)}${if (fromLocation.length > 30) "\u2026" else ""}",
                            fontSize = 13.sp,
                            color = colors.green,
                        )
                    }
                }
            }

            // --- Rating info ---
            if (activity.rating != null) {
                Spacer(Modifier.height(12.dp))
                Card(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 24.dp),
                    shape = RoundedCornerShape(12.dp),
                    colors = CardDefaults.cardColors(containerColor = colors.current),
                ) {
                    Row(
                        modifier = Modifier.padding(16.dp),
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Text("⭐", fontSize = 18.sp)
                        Spacer(Modifier.width(8.dp))
                        Text(
                            text = "Rating: ${String.format(Locale.US, "%.1f", activity.rating)}",
                            fontSize = 14.sp,
                            color = colors.yellow,
                        )
                    }
                }
            }
            } // end if/else isDelay

            Spacer(Modifier.height(80.dp))
        }
    }
}
